export default [
  {
    id: 1,
    TypeAccount: "Compte cheque",
    NumAccount: "12365980002154785",
    Amount: 5000.11,
    deviseType: "MAD",
    Carte: "Card Silver",
    operations: [
      {
        id: 1,
        dateOperation: "06/01/2021",
        description: "Retrait par carte de paiement chez LC WALKIKI Massira CC",
        amount: 300.11,
        deviseType: "MAD",
      },
      {
        id: 2,
        dateOperation: "06/01/2021",
        description: "Retrait par carte de paiement chez Macdonald",
        amount: -600.11,
        deviseType: "MAD",
      },
      {
        id: 3,
        dateOperation: "06/01/2021",
        description: "Retrait par carte de paiement chez LC WALKIKI Massira CC",
        amount: 300.11,
        deviseType: "MAD",
      },
      {
        id: 4,
        dateOperation: "06/01/2021",
        description: "Retrait par carte de paiement chez LC WALKIKI Massira CC",
        amount: -300.11,
        deviseType: "MAD",
      },
      {
        id: 5,
        dateOperation: "06/01/2021",
        description: "Retrait par carte de paiement chez Pizza Hut",
        amount: -150.58,
        deviseType: "MAD",
      },
      {
        id: 6,
        dateOperation: "06/01/2021",
        description: "Retrait par carte de paiement chez LC WALKIKI Massira CC",
        amount: -300.11,
        deviseType: "MAD",
      },
      {
        id: 7,
        dateOperation: "06/01/2021",
        description: "Retrait par carte de paiement chez LC WALKIKI Massira CC",
        amount: 300.01,
        deviseType: "MAD",
      },
    ],
    details: {
      id: 1,
      Titulaire: "Test Test",
      RIB: "213652654956454",
      CodeSwift: "CNCAMAMR",
      Agence: "Agence MAARIFF",
    },
  },
  {
    id: 2,
    TypeAccount: "Compte Épargne",
    NumAccount: "12365980002154785",
    Amount: 2300,
    deviseType: "MAD",
    Carte: "Card Gold",
    operations: [
      {
        id: 1,
        dateOperation: "06/01/2021",
        description: "Retrait par carte de paiement chez LC WALKIKI Massira CC",
        amount: 300.11,
        deviseType: "MAD",
      },
      {
        id: 2,
        dateOperation: "06/01/2021",
        description: "Retrait par carte de paiement chez Macdonald",
        amount: -600.11,
        deviseType: "MAD",
      },
      {
        id: 3,
        dateOperation: "06/01/2021",
        description: "Retrait par carte de paiement chez LC WALKIKI Massira CC",
        amount: 300.11,
        deviseType: "MAD",
      },
      {
        id: 4,
        dateOperation: "06/01/2021",
        description: "Retrait par carte de paiement chez LC WALKIKI Massira CC",
        amount: -300.11,
        deviseType: "MAD",
      },
      {
        id: 5,
        dateOperation: "06/01/2021",
        description: "Retrait par carte de paiement chez Pizza Hut",
        amount: -150.58,
        deviseType: "MAD",
      },
      {
        id: 6,
        dateOperation: "06/01/2021",
        description: "Retrait par carte de paiement chez LC WALKIKI Massira CC",
        amount: -300.11,
        deviseType: "MAD",
      },
      {
        id: 7,
        dateOperation: "06/01/2021",
        description: "Retrait par carte de paiement chez LC WALKIKI Massira CC",
        amount: 300.01,
        deviseType: "MAD",
      },
    ],
    details: {
      id: 1,
      Titulaire: "Test Test",
      RIB: "213652654956454",
      CodeSwift: "CNCAMAMR",
      Agence: "Agence MAARIFF",
    },
  },
];
